//
//  MuscleGroupDetailViewController.swift
//  GymPal
//
//  Created by Yehor Krupiei on 02.03.2023.
//

import UIKit

class MuscleGroupDetailVC: UIViewController {
    
    var exercisesList: [MuscleGroupExercises]!
    
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var titleMuscleGroup: UILabel!
    
    var muscleGroupsNames = ""
    var muscleGroup: MuscleGroup!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        exercisesList = [
            // traps
            MuscleGroupExercises(name: "Dumbell Seated Shrugs",image: UIImage(named: "seatedShrug")!, description: "From a seated position, grasp a dumbbell in each hand and hold them to either side of your body. Keeping your body upright, shrug your shoulders as high as you can. Squeeze at the peak contraction before lowering the dumbbells slowly to the start position. Avoid using momentum to lift the weight and allow the weight you stretch your traps before pulling up for another repetition.", muscleGroup: .traps, presentation: "DumbellSeatedShrugs"),
            MuscleGroupExercises(name: "Dumbbell Shrugs", image: UIImage(named: "dumbbellShrug")!, description: "Begin with your feet underneath your hips, standing tall with the dumbbells at your sides and palms facing inwards (neutral grip).Engage your core by drawing your belly button to your spine.Initiate the movement by drawing your shoulders upwards whilst keeping the chest open and chin in place. Avoid rounding the shoulders and jutting your chin forward. Lift the shoulders to the end of your range of movement, this is very individual so it’s important to work within your capabilities.Squeeze the traps at the top of the movement for a beat and then reverse the movement slowly. This ensures the reps are controlled and maximises on the eccentric (downward) portion of the rep.", muscleGroup: .traps, presentation: "DumbbellShrugs"),
            MuscleGroupExercises(name: "Barbell Shrugs", image: UIImage(named: "barbellShrugs")!, description: "Nothing is better for building the traps than heavy weight. As long as you use good form on the movement, then the heavier the better. Most powerlifters have big traps because of all of the heavy deadlifts they do. Johnnie Jackson is a perfect example of this. He has said he actually doesn't train traps at all and his traps are huge. Whether you choose to train the traps or not is up to you. If you do decide to then you want to do barbell shrugs because you can go heavy on them and nothing is better for building those traps up. Stand up straight with your feet at shoulder width as you hold a barbell with both hands in front of you using a pronated-grip (palms facing the thighs). Tip: Your hands should be a little wider than shoulder width apart. You can use wrist wraps for this exercise for a better grip. This will be your starting position. Raise your shoulders up as far as you can go as you breathe out and hold the contraction for a second.", muscleGroup: .traps, presentation: "BarbellShrugs"),
            MuscleGroupExercises(name: "Behind the Back Shrugs", image: UIImage(named: "backShrugs")!, description: "Stand up straight with your feet at shoulder width as you hold a barbell with both hands behind your back using a pronated grip (palms facing back). Tip: Your hands should be a little wider than shoulder width apart. You can use wrist wraps for this exercise for better grip. This will be your starting position. Raise your shoulders up as far as you can go as you breathe out and hold the contraction for a second. Tip: Refrain from trying to lift the barbell by using your biceps. The arms should remain stretched out at all times. Slowly return to the starting position as you breathe in. Repeat for the recommended amount of repetitions. Variations: You can also rotate your shoulders as you go up, going in a semicircular motion from rear to front. However this version is not good for people with shoulder problems. In addition, this exercise can be performed with the barbell in front of your thighs, with dumbbells by the side, a smith machine or with a shrug machine.", muscleGroup: .traps, presentation: "Behind The Back Shrugs"),
            MuscleGroupExercises(name: "Overhead Shrugs", image: UIImage(named: "overheadShrugs")!, description: "Unrack the bar in a front rack position and press overhead to lockout with a double overhand grip. Inhale and contract the traps to elevate the shoulders. Slowly lower the bar back to the starting position and repeat for the desired number of repetitions. The traps tend to respond well to high reps and explosive movements (e.g. snatch grip high pulls) so program your accessory work accordingly. Limit momentum and excessive jerking or bouncing of the weight. No one cares about how much you shrug. Don’t allow the head to jut forward excessively as you squeeze the traps, this can put the neck in a compromised position and result in an injury. Adding a pause at the top of the movement can help to enhance the mind muscle connection.", muscleGroup: .traps, presentation: "OverheadShrugs"),
            // lats
            MuscleGroupExercises(name: "Pull Ups", image: UIImage(named: "pullUps")!, description: "Start by standing directly below a pull-up bar. Place your hands in an overhand grip with your hands slightly further than shoulder-width apart. If you can’t reach the bar from standing on the floor, you can place a box beneath you and stand on that. Once your hands are holding onto the bar, you’re in your starting position. Inhale, then exhale. Lift your feet up from the floor or box so that you’re hanging from the bar, and engage your core by pulling your belly button in toward your spine. Pull your shoulders back and down. Engaging the muscles in your arms and back, bend your elbows and raise your upper body up toward the bar until your chin is over the bar. You can imagine bringing your elbows toward your hips if that makes the movement easier. As you move, avoid swinging your legs around or shrugging your shoulders up. You want to make sure your shoulder blades remain back and down throughout the exercise.Then extend your elbows and lower your body back down to the starting position. ", muscleGroup: .lats, presentation: "PullUps"),
            MuscleGroupExercises(name: "Machine Pulldown", image: UIImage(named: "machinePullDown")!, description: "Grasp the bar with a wide grip with an overhand, knuckles-up grip. Other positions and grips are possible but start with this standard position. Pull the bar down until it's approximately level with the chin. Exhale on the downward motion. While shifting slightly backward is OK, aim to keep your upper torso stationary. Keep your feet flat on the floor and engage your abs as you pull. The bottom of the motion should be where your elbows can't move downward anymore without moving backward. Be sure to stop at that point and do not go lower. Squeeze the shoulder blades together while maintaining square shoulders. From the bottom position, with the bar close to your chin, slowly return the bar to the starting position while controlling its gradual ascent. Don't let it crash into the weight plates.", muscleGroup: .lats, presentation: "MachinePulldown"),
            MuscleGroupExercises(name: "Barbell Bent Over Row", image: UIImage(named: "barbellBentOverRow")!, description: "Hold onto a barbell with your palms facing down. Bend your knees slightly and bend forward at the waist while keeping your back straight. It should be almost parallel with the floor. The barbell should be directly in front of you; your arms should be perpendicular to the floor. This is the starting position. While keeping your torso stationary, lift the barbell toward you. Your elbows should be kept close to your body. Use only your forearms to hold the weight. When you get to the top, squeeze your back muscles and hold for a few seconds. Slowly lower the barbell back to the starting position. Repeat the process for the number of repetitions in your workout routine.", muscleGroup: .lats, presentation: "BarbellBentOverRow"),
            MuscleGroupExercises(name: "Dumbbell Row Unilateral", image: UIImage(named: "dumbbellRowUnilateral")!, description: "Hold a dumbbell in each hand, shoulder-width, with your palms facing each other. Bend over at a 45-degree angle (no lower) and take a deep breath in. Pull the dumbbells up, toward the sides of your chest, or beside the bottom of your rib cage on an exhale. Lift to the point your range of motion allows.", muscleGroup: .lats, presentation: "DumbbellRowUnilateral"),
            MuscleGroupExercises(name: "Machine Seated Cable Row", image: UIImage(named: "machineSeatedCableRow")!, description: "Sit on the bench with your knees bent and grasp the cable attachment. It often has a triangle handle, but it may be a bar. Position yourself with your knees slightly bent, so you have to reach to grab the handle with outstretched arms without curling the lower back over. Brace the abdominals, and you're ready to row. Pull the handle and weight back toward the lower abdomen while trying not to use the momentum of the row too much by moving the torso backward with the arms. Target the middle to upper back by keeping your back straight and squeezing your shoulder blades together as you row, keeping your chest out. Return the handle forward under tension to full stretch, remembering to keep that back straight even though flexed at the hips. Repeat the exercise for the desired number of repetitions.", muscleGroup: .lats, presentation: "MachineSeatedCableRow"),
            MuscleGroupExercises(name: "Cable Pullover", image: UIImage(named: "cablePullover")!, description: "Face a cable machine with a straight bar attachment slightly higher than head height (for most, this will have the cable pulley at the top of the machine). From here, grab the handle with an overhand grip (about shoulder-width apart) and take a step or two back away from the machine. With the core engaged and shoulders down and back, set feet shoulder width apart and hinge forward slightly. Now, keep your arms straight and pull the bar down - pulling with your lats! Once the straight bar handle attachment reaches your thighs, pause for a moment as you squeeze your lats, then slowly let your arms return to the start position, maintaining your forward hip hinge until all of your reps are complete. Once you have completed your desired number of repetitions, you can then slowly return to an upright position while allowing the bar handle attachment to carefully return to the top (don't just let it go and whip back up, obviously).", muscleGroup: .lats, presentation: "CablePullover"),
            MuscleGroupExercises(name: "Dumbbell Laying Incline Row", image: UIImage(named: "dumbbellLayingInclineRow")!, description: "Set up a bench at a 45° angle and lie face down on it so your chest is in full contact with the bench with your feet on the floor behind you. Let your arms hang down, holding a set of dumbbells with your palms facing each other. Row the weights up by squeezing your shoulder blades together and bringing your elbows back until your upper arms are level with or slightly higher than your torso. Slowly lower the weights back to the start. While the bench is supporting you during the exercise, that doesn’t mean you don’t need to be conscious of your body position. Focus on keeping your chest and abs pressed into the bench – in particular, don’t let your lower back arch away from the bench. This will ensure the exercise isolates the back muscles and stops you creating momentum to assist the lift.", muscleGroup: .lats, presentation: "DumbbellLayingInclineRow"),
            // lower-back
            MuscleGroupExercises(name: "Barbell Deadlift", image: UIImage(named: "barbellDeadlift")!, description: "Start with the feet shoulder width apart (foot stance may vary depending on variation). Feet are under the bar with the bar close to the shins Lower the torso to the bar by pushing the buttocks back and hinging at the waist. Then grasp the bar in your hands. Squeeze the shoulder blades together to engage the lats, followed by engaging the core musculature. Make sure to keep the hips lower than the shoulders and the head/neck in a neutral position. Push through the feet and pull the weight up. Think about pushing the floor away, rather than lifting the weight up. The bar should stay relatively close to the shins. Squeeze the glutes to lock the top of the lift. Lower to the floor the the reverse manner.", muscleGroup: .lowerBack, presentation: "BarbellDeadlift"),
            MuscleGroupExercises(name: "Dumbbell Deadlift", image: UIImage(named: "dumbbellDeadlift")!, description: "Hold a pair of dumbbells in front of you with an overhand grip, palms facing the body. Hinge forward at your hips, slightly bending the knees, lowering the dumbbells to the ground without allowing your back to round. Brace core and lift back to the starting position. Keep your head in line with the rest of your body and avoid overarching at the neck. Be sure to keep the dumbbells close to the body throughout the movement.", muscleGroup: .lowerBack, presentation: "DumbbellDeadlift"),
            MuscleGroupExercises(name: "Machine 45 Degree Back Extension", image: UIImage(named: "machineBackExtension")!, description: "Keep your feet flat on the support. Maintain straight legs. Position your thighs on the pads of the chair so that your hips are free to flex. As an alternative, you can clasp your hands behind your head (instead of crossing your arms over your chest) to keep your upper body steady. Keep your movement slow and controlled. Do not extend back beyond the start position as you may injure your back. Look for your body to move forwards from the lower gluteal, not your back or spine. Avoid improper positioning  (your hip bones should be in direct contact with the pads). Don’t jerk your torso as you raise it back up to the starting position. 45-Degree Lumbar Extension", muscleGroup: .lowerBack, presentation: "Machine45DegreeBackExtension"),
            // shoulders
            MuscleGroupExercises(name: "Dumbbell Lateral Raise", image: UIImage(named: "dumbbellLateralRaise")!, description: "Stand tall, a dumbbell in each hand. Arms are at your sides, palms facing in. Position your feet roughly hip-distance apart. Check your posture—roll your shoulders back, engage your core, and look straight ahead. Raise your arms simultaneously just a couple inches out to each side and pause. This momentary pause should help ensure you disengage your trapezius muscle from the movement, targeting the deltoids as intended. Lift the dumbbells up and out to each side, keeping your arms almost completely straight, stopping when your elbows reach shoulder-height and your body is forming a T shape. Breathe in as you lift. Pause and hold for a second at the top of the movement. Lower the weights slowly (take about twice as long to lower the weights as you took to lift them), bringing your arms back to your sides. Breathe out as you lower the dumbbells.", muscleGroup: .shoulders, presentation: "DumbbellLateralRaise"),
            MuscleGroupExercises(name: "Dumbbell Seated Overhead Press", image: UIImage(named: "dumbbellSeatedOverhead")!, description: "Set up an adjustable angle bench to 90 degrees and select the desired weight from the rack. Pick up the dumbbells from the floor using a neutral grip (palms facing in). Position the end of the dumbbells on your knees and sit down on the bench. Using a safe and controlled motion, kick your knees up one at a time in order to get each dumbbell into place. Once the dumbbells are in place, rotate your palms so they are facing forward. Take a deep breath then press the dumbbells overhead by extending the elbows and contracting the deltoids. Slowly lower the dumbbells back to the starting position (the arms should be roughly 90 degrees or slightly lower depending upon limb lengths). Repeat for the desired number of repetitions.", muscleGroup: .shoulders, presentation: "DumbbellSeatedOverheadPress"),
            MuscleGroupExercises(name: "Dumbbell Front Raise", image: UIImage(named: "dumbbellFrontRaise")!, description: "Start by standing with your feet shoulder-width apart and holding a dumbbell in each hand at arm's length in front of you with your palms facing your thighs.Slowly raise the dumbbells up to shoulder height. Hold the dumbbells roughly 4 inches away from your body. Pause for a moment when you reach the top before lowering them back down to the starting position. That's one rep. Repeat for the desired number of reps. Use a lightweight to start. You can increase the weight as you get comfortable. Keep your abdominal muscles pulled in, and avoid swinging the weights as you raise and lower them. Don't arch your back as you lift the weights. Instead, keep your spine in a neutral position. To make this exercise more challenging, try lifting one dumbbell at a time.", muscleGroup: .shoulders, presentation: "DumbbellFrontRaise"),
            MuscleGroupExercises(name: "Reverse Butterfly", image: UIImage(named: "reverseButterfly")!, description: "To begin with, your seat should be adjusted so that your shoulders are at the same height as the wrists of the exercise machine. Sit on the backrest and press your chest against the seat of the machine. Your feet are flat and your legs are on either side of the bench. Place each of your hands on the wrists provided for this purpose. The arms should be almost straight and you should catch the wrists in a pronated grip. Spread your arms as far back as possible, then return to your starting position. The back must always remain straight and the movement of quality. When you perform the exercise, your pectoral muscles must come out to the maximum. the exercise can be slower to play with the power-on time. Control the tempo of the exercise. The loads should be appropriate and not too heavy. Keep a slight bend in the elbow. This workout will challenge your deltoids and shoulders. It will isolate the posterior deltoid and the back shoulder portion.", muscleGroup: .shoulders, presentation: "ReverseButterfly"),
            MuscleGroupExercises(name: "Barbell Overhead Press", image: UIImage(named: "barbellOverheadPress")!, description: "Setup. Stand with the bar on your front shoulders. Narrow grip, straight wrists, vertical forearms. Lock your knees and hips.  Lift Your Chest. Raise your chest towards the ceiling by arching your upper-back. Try to touch your chin with your upper-chest. Press. Take a big breath, hold it and press the bar in a vertical line. Don’t press it in front or behind your head. Press it over your head. Move Forward. Stay close to the bar while you press the weight up. Shift your torso forward once the bar has passed your forehead. Lockout. Hold the bar over your shoulders and mid-foot for proper balance. Lock your elbows. Shrug your shoulders to the ceiling. ", muscleGroup: .shoulders, presentation: "BarbellOverheadPress"),
            MuscleGroupExercises(name: "Elevated Pike Press", image: UIImage(named: "elevatedPikePress")!, description: " Get down on your hands and feet, with your hands shoulder-width apart, your legs straight and your hips up.  Bend your elbows, until your arms form a 90-degree angle, and bring your head close to the mat.  Straighten your elbows, pushing your body away from the mat, and return to the starting position. Repeat until the set is complete.", muscleGroup: .shoulders, presentation: "ElevatedPikePress"),
            MuscleGroupExercises(name: "Barbell Upright Row", image: UIImage(named: "barbellUprightRow")!, description: "Stand with your feet shoulder-width apart. Grasp the barbell and allow it to hang in front of you at the length of your arms. Your palms should be facing your body and your hands in line with the thighs.Breathe in and brace the abdominals. Keep your back straight, chest up, and eyes focused forward. Lift the barbell up (toward the chin) as you exhale. Lead with the elbows and keep the bar close to the body. Pause at the top of the lift. Lower the barbell as you inhale, returning it to the starting position.", muscleGroup: .shoulders, presentation: "BarbellUprightRow"),
            // chest
            MuscleGroupExercises(name: "Push Up", image: UIImage(named: "pushUp")!, description: "To do a push-up you are going to get on the floor on all fours, positioning your hands slightly wider than your shoulders. Don't lock out the elbows; keep them slightly bent. Extend your legs back so you are balanced on your hands and toes, your feet hip-width apart. Once in this position, here is how you will do a push-up. Contract your abs and tighten your core by pulling your belly button toward your spine.  Inhale as you slowly bend your elbows and lower yourself to the floor, until your elbows are at a 90-degree angle. Exhale while contracting your chest muscles and pushing back up through your hands, returning to the start position. ", muscleGroup: .chest, presentation: "Push Up"),
            MuscleGroupExercises(name: "Barbell Bench Press", image: UIImage(named: "barbellBenchPress")!, description: "Lie on your back on a flat bench. Grip a barbell with hands slightly wider than shoulder width. The bar should be directly over the shoulders. Press your feet firmly into the ground and keep your hips on the bench throughout the entire movement.  Keep your core engaged and maintain a neutral spine position throughout the movement. Avoid arching your back.Slowly lift the bar or dumbbells off the rack, if using. Lower the bar to the chest, about nipple level, allowing elbows to bend out to the side, about 45 degrees away from the body. Stop lowering when your elbows are just below the bench. Press feet into the floor as you push the bar back up to return to starting position.", muscleGroup: .chest, presentation: "Barbell Bench Press"),
            MuscleGroupExercises(name: "Dumbbell Incline Bench Press", image: UIImage(named: "dumbbellBenchPress")!, description: "Sit on the bench and lean back. Hold a dumbbell in each hand, with hands positioned at your shoulders, elbows bent and angled down below your ribs. Relax your neck against the bench. Keep your feet flat on the floor. Brace your core and press both dumbbells straight over your chest as you exhale. Keep your wrists straight (don't let them cock backward). At the top of the movement, the dumbbells should almost touch each other, and your arms should be perpendicular to the floor.Reverse the movement and slowly lower the dumbbells to the top of your chest as you inhale. As you lower the dumbbells, your elbows should come down at roughly a 45-degree angle to your torso. They shouldn't splay out to the sides, pointing toward the side of the room. Instead, keep your elbows pointing to the floor. When you finish your set, safely exit the exercise by sitting up and placing the dumbbells on your knees before you stand up. Avoid dropping the dumbbells while you're lying on the incline bench.", muscleGroup: .chest, presentation: "Dumbbell Incline Bench Press"),
            MuscleGroupExercises(name: "Dumbbell Incline Chest Flys", image: UIImage(named: "dumbbellChestFlys")!, description: "Adjust the bench to a 30 to 45-degree incline position. Sit down, straddling the bench with both feet flat on the floor. Lie back and raise the dumbbells over your chest. Your elbows are slightly bent with palms facing each other—as if hugging a barrel over your chest. This is the starting position. Inhale and slowly lower the dumbbells in an arc position until you feel a mild stretch in your chest or shoulders. Exhale and bring the weights back to the starting position, maintaining an arc throughout the movement. Return the dumbbells to your body's center once this exercise is completed. Rest the weights on your chest or thighs, depending on weight, as you exhale and use your core to sit up.", muscleGroup: .chest, presentation: "Dumbbell Incline Chest Flys"),
            MuscleGroupExercises(name: "Barbell Incline Bench Press", image: UIImage(named: "barbellInclineBenchPress")!, description: "Position your body on an incline bench on a 30-45 degree angle. Grab a barbell with an overhand grip that's shoulder-width apart and hold it above your chest. Extend arms upward, locking out elbows.Lower the bar straight down in a slow, controlled movement to your chest. Pause, then press the bar in a straight line back up to the starting position.Do not lower the bar to the neck. Bring the bar to the upper part of your chest on the descent.Do not hyper extend the neck. Maintain a neutral long spine. Do not bounce the bar off of the chest. Lower the bar with control.", muscleGroup: .chest, presentation: "Barbell Incline Bench Press"),
            MuscleGroupExercises(name: "Dips", image: UIImage(named: "dips")!, description: "Grab both handles of a dip bar station, then press yourself upward by straightening your arms and gently jumping off the ground so that your arms are straight and supporting your entire body weight with your hands underneath your shoulders. Without bending your elbows, tuck your shoulder blades down and squeeze them together. A good cue for this is to imagine moving your shoulders toward the floor, away from your ears, and pinching a pencil between your shoulder blades. Lean forward slightly, then bend your knees and cross your feet over each other behind you if you find it more comfortable. Lower your body by bending your elbows, allowing your elbows to flare about 6-to-8 inches from your sides, until your arms are at a 90-degree angle. Don’t roll your shoulders forward or allow your shoulder blades to shift apart or upward.Press upward and return to the starting position.", muscleGroup: .chest, presentation: "Dips"),
            MuscleGroupExercises(name: "Butterfly", image: UIImage(named: "butterfly")!, description: "Sit on the machine with your back flat on the pad.Take hold of the handles. Tip: Your upper arms should be positioned parallel to the floor; adjust the machine accordingly. This will be your starting position. Push the handles together slowly as you squeeze your chest in the middle. Breathe out during this part of the motion and hold the contraction for a second. Return back to the starting position slowly as you inhale until your chest muscles are fully stretched. Repeat for the recommended amount of repetitions.", muscleGroup: .chest, presentation: "Butterfly"),
            MuscleGroupExercises(name: "Cable Crossover", image: UIImage(named: "cableCrossover")!, description: "To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand. Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position. With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement.Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights.", muscleGroup: .chest, presentation: "Cable Crossover"),
            // triceps
            MuscleGroupExercises(name: "Cable Push Down", image: UIImage(named: "cablePushDown")!, description: "Start off standing in front of a cable machine, attaching a rope to the high pulley and grabbing the attachment with an overhand (palms down) grip. Keeping your abs drawn in, back straight and elbows in at your sides, push the rope down towards your thighs. As you push down towards your thighs, split the rope apart at the bottom and isolate the tricep muscle. Hold this position for a count and return back up to the starting position. Repeat for as many reps and sets as desired.", muscleGroup: .triceps, presentation: "Cable Push Down"),
            MuscleGroupExercises(name: "Dips", image: UIImage(named: "dips")!, description: "Grab both handles of a dip bar station, then press yourself upward by straightening your arms and gently jumping off the ground so that your arms are straight and supporting your entire body weight with your hands underneath your shoulders. Without bending your elbows, tuck your shoulder blades down and squeeze them together. A good cue for this is to imagine moving your shoulders toward the floor, away from your ears, and pinching a pencil between your shoulder blades. Lean forward slightly, then bend your knees and cross your feet over each other behind you if you find it more comfortable. Lower your body by bending your elbows, allowing your elbows to flare about 6-to-8 inches from your sides, until your arms are at a 90-degree angle. Don’t roll your shoulders forward or allow your shoulder blades to shift apart or upward.Press upward and return to the starting position.", muscleGroup: .triceps, presentation: "Dips"),
            MuscleGroupExercises(name: "Barbell Close Grip Bench Press", image: UIImage(named: "barbellGripBenchPress")!, description: "Position the barbell at the correct reach level on the rack (you should be able to grip/lift the bar off the rack with assistance).Load weight resistance according to your fitness level onto the barbell.Lie flat on the bench and grip the bar with your hands shoulder-width apart.Lift the bar with assistance from the rack, arms locked, and hold the bar straight over you. Inhale and slowly bring the bar down toward your chest, keeping your elbows close to your body for the entire exercise. Exhale and push the bar up using the triceps and locking arms at the top of the movement.", muscleGroup: .triceps, presentation: "Barbell Close Grip Bench Press"),
            MuscleGroupExercises(name: "Bench Dips", image: UIImage(named: "benchDips")!, description: "Sit down on a bench, hands next to your thighs. (You can also perform a bench dip off a stair or other elevated surface; the same steps apply.)Walk your feet out and extend your legs, lifting your bottom off the bench and holding there with extended arms. Hinging at the elbow, lower your body down as far as you can go, or until your arms form a 90-degree angle.Push up through your palms back to start.", muscleGroup: .triceps, presentation: "Bench Dips"),
            MuscleGroupExercises(name: "Barbell Skullcrushers", image: UIImage(named: "skullCrushers")!, description: "Starting Position: Start lying on your back on your bench with your feet on the floor. Grip your barbell with your hands about shoulder-width apart and your palms facing away from you. Extend your arms all the way, locking out your elbows with the barbell suspended above your chest. Lower the barbell towards your forehead, keeping your elbows as tucked in as possible. Be sure to keep a tight grip on your barbell as you bring the weight down. Once the barbell reaches your forehead, lower the bar behind your head in a slow and controlled motion. You will feel your shoulders lower and your arms roll back as you complete this step. You should feel it in the back of your arm.Pause at the bottom.Lift the bar back to your starting position, following the same path of movement that the bar took on the way down. Continue to focus on keeping your elbows tucked and your grip tight on the barbell.", muscleGroup: .triceps, presentation: "Barbell Skullcrushers"),
            MuscleGroupExercises(name: "Cable Skullcrusher", image: UIImage(named: "cableSkullcrusher")!, description: "Attach a double-handled rope attachment to the high setting on a cable machine. Take the handles in each hand and take them overhead as you turn around, so that you end up with your back to the machine and the rope handles in each hand behind your neck. Stand tall with your elbows bent but held high, and your hands together. rom the starting position, straighten your elbows to bring your hands straight up into the air, ending with your arms fully extended above you and slightly in front of vertical. Your motion should be controlled but swift and powerful, as though you were throwing the handles toward the ceiling; focus on engaging your triceps. Bend your elbows to return your hands to the starting position, letting your triceps stretch at the bottom of your movement.", muscleGroup: .triceps, presentation: "Cable Skullcrusher"),
            // biceps
            MuscleGroupExercises(name: "Barbell Curl", image: UIImage(named: "barbellCurl")!, description: "The standing barbell curl is the cornerstone of many bicep building routines. Grasp a barbell or Olympic bar at around shoulder width apart using an underhand grip (palms facing up).Stand straight up, feet together (you may be more comfortable putting one foot back for stability), back straight, and with your arms fully extended.The bar should not be touching your body.Keeping your eyes facing forwards, elbows tucked in at your sides, and your body completely still, slowly curl the bar up.Squeeze your biceps hard at the top of the movement, and then slowly lower it back to the starting position. The single biggest mistake lifters make on this exercise is swinging the body back to assist in moving the weight up. This is cheating! Your body should remain fixed and only your biceps should be used to move the weight.Another mistake is not keeping the elbows fixed and in at the sides. You should not let your elbows come forward when moving the weight up.", muscleGroup: .biceps, presentation: "Barbell Curl"),
            MuscleGroupExercises(name: "Chin Ups", image: UIImage(named: "chinUps")!, description: "Using a supinated grip, grasp the bar with a shoulder width grip. Take a deep breath, squeeze your glutes and brace your abs. Depress the shoulder blades and then drive the elbows straight down to the floor while activating the lats. Pull your chin towards the bar until the lats are fully contracted, then slowly lower yourself back to the start position and repeat for the assigned number of repetitions.", muscleGroup: .biceps, presentation: "Chin Ups"),
            MuscleGroupExercises(name: "Dumbbell Curl", image: UIImage(named: "dumbbellCurl")!, description: "Stand by holding a dumbbell in each hand with your arms hanging by your sides. Ensure your elbows are close to your torso and your palms facing forward. Keeping your upper arms stationary, exhale as you curl the weights up to shoulder level while contracting your biceps.", muscleGroup: .biceps, presentation: "Dumbbell Curl"),
            MuscleGroupExercises(name: "Dumbbell Hammer Curl", image: UIImage(named: "dumbbellHammerCurl")!, description: "Stand with your legs straight (but not stiff or locked) and knees aligned under the hips. Your arms are at your side with a dumbbell in each hand, the weights resting next to the outer thigh. Your palms are facing the thighs, the thumbs are facing forward, and your shoulders are relaxed.Bend at the elbow, lifting the lower arms to pull the weights toward the shoulders. Your upper arms are stationary and the wrists are in line with the forearms. Hold for one second at the top of the movement. Your thumbs will be close to the shoulders and palms facing in, toward the midline of the body. Lower the weights to return to the starting position.", muscleGroup: .biceps, presentation: "Dumbbell Hammer Curl"),
            MuscleGroupExercises(name: "Dumbbell Concentration Curl", image: UIImage(named: "dumbbellConcentrationCurl")!, description: "Sit on a bench, with a dumbbell between your legs. Grab the dumbbell with one hand, then place your upper arm (your triceps muscle) against your thigh. Your goal should be to keep your arm perpendicular to the ground throughout the whole movement. Tighten your core and engage your shoulder blades to create tension and reinforce posture. Make a fist with your off hand and extend your non-working arm out to the side. This allows you to use your core to balance and remove any leverage that would take away from biceps engagement. Curl the weight up with control, keeping the wrist in a neutral position. Emphasize the squeeze at the top of the rep; avoid any backwards lean or shoulder movement, keeping the focus on the biceps.", muscleGroup: .biceps, presentation: "Dumbbell Concentration Curl"),
            MuscleGroupExercises(name: "Barbell Preacher Curl", image: UIImage(named: "barbellPreacherCurl")!, description: "Sit down on the preacher bench and adjust the seat height so your upper arms and chest are both in contact with the pad. Lean forward and grip the E Z bar, which should be placed on the front bar rest, with an underhand grip around shoulder-width apart. Tuck your chin in with your arms extended and maintain a neutral wrist. Curl by squeezing your bicep and bending your elbows, lifting until the bar is at shoulder height. Make sure to keep the upper arms in contact with the pad the entire exercise.Slowly lower your arms to the starting position and reset and repeat.", muscleGroup: .biceps, presentation: "Barbell Preacher Curl"),
            // forearms
            MuscleGroupExercises(name: "Dumbbell Wrist Extension", image: UIImage(named: "dumbbellWristExtension")!, description: "Grab a dumbbell with an overhand grip and rest your forearm against your thigh, or alternatively against a bench.Lower your hand towards the floor. Reverse the motion by bending your wrist upwards.", muscleGroup: .forearms, presentation: "Dumbbell Wrist Extension"),
            MuscleGroupExercises(name: "Barbell Wrist Curl", image: UIImage(named: "barbellWristCurl")!, description: "Sit on a flat bench, leaning forward. Grasp barbell with an underhand grip (palms up) and rest forearms on either the bench or thighs. Using your wrists alone, curl the weight upward, exhaling throughout the movement. Slowly lower the weight as low as is comfortable, inhaling throughout the movement.", muscleGroup: .forearms, presentation: "Barbell Wrist Curl"),
            MuscleGroupExercises(name: "Barbell Behind The Back Wrist Curl", image: UIImage(named: "barbellBackWristCurl")!, description: "Standing tall, place a barbell behind your back, your hands shoulder-width apart and your palms facing behind you. Your arms should be fully extended so the bar rests just below your glutes. Flexing your wrists, curl the barbell toward your body. Pause, then lower the bar to the starting position. Perform the movement in a slow and controlled manner. With each rep, make sure to move through your full range of motion.", muscleGroup: .forearms, presentation: "Barbell Behind The Back Wrist Curl"),
            //obliques
            MuscleGroupExercises(name: "Dumbbell Wood Chopper", image: UIImage(named: "dumbbellWoodChopper")!, description: "Attach a hand grip to the cable machine, positioning the cable anchor near the top of the frame using the adjustable mechanism. Load the machine with sufficient weight to provide moderate resistance. Position your body so that the cable movement will be downward and across the body—like a tree-chopping action. Extend the arms and grasp the cable handle with both hands above one shoulder, keeping the feet shoulder-width apart, a neutral spine, and knees slightly bent. Pull the handle downward and diagonally across the body slowly, until it passes the opposite thigh. Rotate the entire torso during the pull and keep the arms fully extended throughout the movement. Hold for a count of one or two. Perform the movement in reverse, returning the cable handle to the starting position.", muscleGroup: .obliques, presentation: "Dumbbell Wood Chopper"),
            MuscleGroupExercises(name: "Dumbbell Overhead Side Bend", image: UIImage(named: "dumbbellOverheadSideBend")!, description: "Hold the dumbbell above your head, squeezing your ears with your upper arms to activate your core. Pull your abs to your spine and lengthen your spine as you bend slowly to the right. Return to standing upright, and then slowly to the left. Keep your pelvis still as you bend to the side.", muscleGroup: .obliques, presentation: "Dumbbell Overhead Side Bend"),
            MuscleGroupExercises(name: "Dumbbell Russian Twist", image: UIImage(named: "dumbbellRussianTwist")!, description: "Sit on the floor with knees bent in the sit-up position. Lean back at a 45 degree angle. Keep your heels in contact with the floor. Brace your core and squeeze your glutes. Rotate the dumbbell over your body from side to side, keeping it just off the floor. Keep your chin tucked in, head moving in line with the shoulders. Rotate at the waist and keep your shoulders square and straight. Avoid rounding your spine. Keep your chest up and open.", muscleGroup: .obliques, presentation: "Dumbbell Russian Twist"),
            // abdominals
            MuscleGroupExercises(name: "Hanging Knee Raises", image: UIImage(named: "hangingKneeRaises")!, description: "Hanging knee raises are a bodyweight exercise that targets your central core and lower abs. You do them by lifting and lowering your knees while hanging on a pull-up bar. Hanging knee raises require great upper-body strength. You can modify the move by doing it while lying down. Double crunches and bicycle kicks are some alternatives to hanging knee raises. If you’re not sure if this move is right for you, reach out to a certified personal trainer for advice.", muscleGroup: .abdominals, presentation: "Hanging Knee Raises"),
            MuscleGroupExercises(name: "Lying Leg Raises", image: UIImage(named: "lyingLegRaises")!, description: "Lie on your back, legs straight and together. Keep your legs straight and lift them all the way up to the ceiling until your butt comes off the floor.  Slowly lower your legs back down till they’re just above the floor. Hold for a moment. Raise your legs back up. Repeat.", muscleGroup: .abdominals, presentation: "Lying Leg Raises"),
            MuscleGroupExercises(name: "Crunches", image: UIImage(named: "crunches")!, description: "Lie down on your back. Plant your feet on the floor, hip-width apart. Bend your knees and place your arms across your chest. Contract your abs and inhale. Exhale and lift your upper body, keeping your head and neck relaxed.Inhale and return to the starting position.", muscleGroup: .abdominals, presentation: "Crunches"),
            MuscleGroupExercises(name: "Machine Roll Outs", image: UIImage(named: "machineRollOuts")!, description: "Hold an Olympic barbell loaded with 5-10lbs on each side and kneel on the floor. Now place the barbell on the floor in front of you so that you are on all your hands and knees (as in a kneeling push up position). This will be your starting position. Slowly roll the barbell straight forward, stretching your body into a straight position. Tip: Go down as far as you can without touching the floor with your body. Breathe in during this portion of the movement. After a second pause at the stretched position, start pulling yourself back to the starting position as you breathe out. Tip: Go slowly and keep your abs tight at all times.", muscleGroup: .abdominals, presentation: "Machine Roll Outs"),
            MuscleGroupExercises(name: "Sit Ups", image: UIImage(named: "sitUps")!, description: "Lie down on your back, keep your knees bent, and your back and feet flat on the mat. Slowly lift your torso and sit up. Return to the starting position by rolling down one vertebra at a time. Repeat the exercise until set is complete.", muscleGroup: .abdominals, presentation: "Sit Ups"),
            // quads
            MuscleGroupExercises(name: "Barbell Squat", image: UIImage(named: "barbellSquat")!, description: "Set up for the exercise by setting the barbell to just below shoulder height and loading the weight you want to use. Stand under the bar with your feet at about shoulder width apart. Position the bar so that it is resting on the muscles on the top of your back, not on the back of your neck. The bar should feel comfortable. If it doesn't, try adding some padding to the bar. Now take your hands over the back and grip the bar with a wide grip for stability. You should now bend at the knees and straighten your back in preparation to take the weight off the rack.Keeping your back straight and eyes up, push up through the legs and take the weight off the rack. Take a small step back and stabilize yourself. Keeping your eyes facing forward slowly lower your body down. Don't lean forward as you come down. Your buttocks should come out and drop straight down.Squat down until your thighs are parallel with the floor, and then slowly raise your body back up by pushing through your heels.", muscleGroup: .quads, presentation: "Barbell Squat"),
            MuscleGroupExercises(name: "Forward Lunges", image: UIImage(named: "forwardLunges")!, description: "Stand tall with feet hip-width apart. Engage your core.Take a big step forward with right leg. Start to shift your weight forward so heel hits the floor first. Lower your body until right thigh is parallel to the floor and right shin is vertical. It’s OK if knee shifts forward a little as long as it doesn’t go past right toe. If mobility allows, lightly tap left knee to the floor while keeping weight in right heel.Press into right heel to drive back up to starting position.Repeat on the other side.", muscleGroup: .quads, presentation: "Forward Lunges"),
            MuscleGroupExercises(name: "Machine Leg Extension", image: UIImage(named: "legExtension")!, description: "Set up the leg extension machine so the pad is at the top of your lower legs at the ankles. Your knees are at 90 degrees. Select a weight that will give you a moderate load for 10 to 12 repetitions. Place your hands on the hand bars. Lift the weight while exhaling until your legs are almost straight. Do not lock your knees. Keep your back against the backrest and do not arch your back. Exhale and lower the weight back to starting position.", muscleGroup: .quads, presentation: "Machine Leg Extension"),
            MuscleGroupExercises(name: "Machine Leg Press", image: UIImage(named: "legPress")!, description: "Load the machine with the desired weight and take a seat. Sit down and position your feet on the sled with a shoulder width stance. Take a deep breath, extend your legs, and unlock the safeties. Lower the weight under control until the legs are roughly 45 degrees or slightly below. Drive the weight back to the starting position by extending the knees but don’t forcefully lockout. Repeat for the desired number of repetitions. To keep tension on the quads, keep the knees just shy of lockout. To emphasize the glutes more, push through the heels.To emphasize the quads more, push through the balls of the feet. Don’t allow the hips to posteriorly tilt and roll off the pad.Keep your low back flat against the pad throughout the movement.Maintain a neutral head position by not looking up or down excessively. Self spotting is possible by simply applying pressure to the knees with the hands. Use only when necessary.", muscleGroup: .quads, presentation: "Machine Leg Press"),
            MuscleGroupExercises(name: "Step Up", image: UIImage(named: "stepUp")!, description: "Depending on your hip mobility and strength, place your foot on a box so your knee is bent at a 90-degree angle or the hip crease is slightly below your knee. Ensure it’s on a level surface. Either perform with body weight, hold dumbbells by your side, and stand around one foot away from the box. Place your entire lead foot on the box with your toes pointed forward. Push through your lead foot to stand up. Think of driving in glutes forward into hip extension as you stand up. Once your knee is extended, either place the other foot on the box, balance on one leg, or drive your non-working leg into a high knee. Step down slowly with the non-lead leg and reset and repeat.", muscleGroup: .quads, presentation: "Step Up"),
            // hamstrings
            MuscleGroupExercises(name: "Barbell Stiff Leg Deadlifts", image: UIImage(named: "stiffLegDeadlifts")!, description: "Position the bar over the top of your shoelaces and assume a hip width stance. Push your hips back and hinge forward until your torso is nearly parallel with the floor. Reach down and grasp the bar using a shoulder width, double overhand grip. Ensure your spine is neutral, shin is vertical, and your hips are roughly the same height as your shoulders. Drive through the whole foot and focus on pushing the floor away. Ensure the bar tracks in a straight line as you extend the knees and hips. Once you have locked out the hips, reverse the movement by pushing the hips back and hinging forward. Return the bar to the floor, reset, and repeat for the desired number of repetitions.", muscleGroup: .hamstrings, presentation: "Barbell Stiff Leg Deadlifts"),
            MuscleGroupExercises(name: "Machine Hamstring Curl", image: UIImage(named: "hamstringCurl")!, description: "Lie face down on the lying leg curls machine, stretching your legs out fully. The roller pad should rest just above the heels, a few inches over your calves. Grasp the support handles on each side of the machine. Exhale and flex your knees, pulling your ankles as close to your buttocks as possible. Keep your hips firmly on the bench. Hold briefly.Inhale as you return your feet to the starting position in a slow and controlled movement.", muscleGroup: .hamstrings, presentation: "Machine Hamstring Curl"),
            MuscleGroupExercises(name: "Barbell Low Bar Good Morning", image: UIImage(named: "goodMorning")!, description: "Set up the barbell in the squat rack as you would for your barbell back squat. Duck under the barbell and place the barbell in your preferred position on your upper back. Unrack the barbell and walk back two or three steps. Get your feet roughly shoulder-width apart. With a slight bend in your knees, hinge at the hips while keeping your chest up and shoulders down. Stop when your torso is almost parallel to the floor.Then lift yourself to a standing position by contracting your glutes and hamstrings.Reset neutral posture and repeat for appropriate reps.", muscleGroup: .hamstrings, presentation: "Barbell Low Bar Good Morning"),
            MuscleGroupExercises(name: "Dumbbell Romanian Deadlift", image: UIImage(named: "romanianDeadlift")!, description: "Begin in a standing position with a dumbbell in each hand. Ensure that your back is straight and stays that way for the duration of the exercise. Allow your arms to hang perpendicular to the floor, with the wrists pronated and the elbows pointed to your sides. This will be your starting position. Initiate the movement by flexing your hips, slowly pushing your butt as far back as you can. This should entail a horizontal movement of the hips, rather than a downward movement. The knees should only partially bend, and your weight should remain on your heels. Drive your butt back as far as you can, which should generate tension in your hamstrings as your hands approach knee level. Maintain an arch in your back throughout the exercise. When your hips cannot perform any further backward movement, pause, and then slowly return to the starting position by extending the hips.", muscleGroup: .hamstrings, presentation: "Dumbbell Romanian Deadlift"),
            // glutes
            MuscleGroupExercises(name: "Barbell Squat", image: UIImage(named: "barbellSquat")!, description: "Set up for the exercise by setting the barbell to just below shoulder height and loading the weight you want to use. Stand under the bar with your feet at about shoulder width apart. Position the bar so that it is resting on the muscles on the top of your back, not on the back of your neck. The bar should feel comfortable. If it doesn't, try adding some padding to the bar. Now take your hands over the back and grip the bar with a wide grip for stability. You should now bend at the knees and straighten your back in preparation to take the weight off the rack.Keeping your back straight and eyes up, push up through the legs and take the weight off the rack. Take a small step back and stabilize yourself. Keeping your eyes facing forward slowly lower your body down. Don't lean forward as you come down. Your buttocks should come out and drop straight down.Squat down until your thighs are parallel with the floor, and then slowly raise your body back up by pushing through your heels.", muscleGroup: .glutes, presentation: "Barbell Squat"),
            MuscleGroupExercises(name: "Barbell Hip Thrust", image: UIImage(named: "barbellHipThrust")!, description: "Start seated on the floor, knees bent, feet slightly wider than hip-distance apart. The toes can be turned out just slightly. The upper back (lower scapula) should be resting against the edge of the weight bench in the center of the bench. Place the weight bar across the hips. Hold onto the bar to keep it in place, but do not use your arms to lift it. Squeeze the glutes and press the bar straight up until the hips are in line with the shoulders and knees. The bench should be supporting the mid-scapula area. Keep the core tight and maintain a slight chin tuck with your focus down your body (a few inches above the bar). Slowly lower the bar down until the hips are just a few inches off the floor. Squeeze the glutes and lift again.", muscleGroup: .glutes, presentation: "Barbell Hip Thrust"),
            MuscleGroupExercises(name: "Forward Lunges", image: UIImage(named: "forwardLunges")!, description: "Stand tall with feet hip-width apart. Engage your core.Take a big step forward with right leg. Start to shift your weight forward so heel hits the floor first. Lower your body until right thigh is parallel to the floor and right shin is vertical. It’s OK if knee shifts forward a little as long as it doesn’t go past right toe. If mobility allows, lightly tap left knee to the floor while keeping weight in right heel.Press into right heel to drive back up to starting position.Repeat on the other side.", muscleGroup: .glutes, presentation: "Forward Lunges"),
            MuscleGroupExercises(name: "Barbell Low Bar Good Morning", image: UIImage(named: "goodMorning")!, description: "Set up the barbell in the squat rack as you would for your barbell back squat. Duck under the barbell and place the barbell in your preferred position on your upper back. Unrack the barbell and walk back two or three steps. Get your feet roughly shoulder-width apart. With a slight bend in your knees, hinge at the hips while keeping your chest up and shoulders down. Stop when your torso is almost parallel to the floor.Then lift yourself to a standing position by contracting your glutes and hamstrings.Reset neutral posture and repeat for appropriate reps.", muscleGroup: .glutes, presentation: "Barbell Low Bar Good Morning"),
            MuscleGroupExercises(name: "Dumbbell Romanian Deadlift", image: UIImage(named: "romanianDeadlift")!, description: "Begin in a standing position with a dumbbell in each hand. Ensure that your back is straight and stays that way for the duration of the exercise. Allow your arms to hang perpendicular to the floor, with the wrists pronated and the elbows pointed to your sides. This will be your starting position. Initiate the movement by flexing your hips, slowly pushing your butt as far back as you can. This should entail a horizontal movement of the hips, rather than a downward movement. The knees should only partially bend, and your weight should remain on your heels. Drive your butt back as far as you can, which should generate tension in your hamstrings as your hands approach knee level. Maintain an arch in your back throughout the exercise. When your hips cannot perform any further backward movement, pause, and then slowly return to the starting position by extending the hips.", muscleGroup: .glutes, presentation: "Dumbbell Romanian Deadlift"),
            // calves
            MuscleGroupExercises(name: "Machine Standing Calf Raises", image: UIImage(named: "standingCalfRaises")!, description: "Adjust the shoulder pad corresponding to your height. Step underneath the pad and place the balls of your feet on the platform with your toes pointed straight ahead - your heels will naturally hang off. Extend the hips and knees in order to raise the shoulder pad. Lower the heels by dorsiflexing the ankles until the calves are fully stretched. Extend the ankles and exhale as you flex the calves. Repeat for the assigned number of repetitions. Keep the repetitions slow and controlled. Limit momentum and pause at the top to emphasize the contraction. If you experience any sort of pain or pressure in the back of the knee joint, keep a slight bend in the knee and avoid complete lockout. If the knee isn’t entirely locked out then ensure the position doesn’t change during the duration of the repetition. Limit depth of the heels if you feel any sort of stretch through the bottom of the foot during the exercise. Try to move through the ball of the foot rather than the base of the toes.", muscleGroup: .calves, presentation: "Machine Standing Calf Raises"),
            MuscleGroupExercises(name: "Machine Seated Calf Raises", image: UIImage(named: "seatedCalfRaises")!, description: "Take a seat on the machine and place the balls of your feet on the platform with your toes pointed forward - your heels will naturally hang off. Position the base of quads under the knee pad and allow your hands to rest on top. Extend your ankles and release the safety bar. Lower the heels by dorsiflexing the ankles until the calves are fully stretched. Extend the ankles and exhale as you flex the calves. Repeat for the assigned number of repetitions. Keep the repetitions slow and controlled. Limit momentum and pause at the top to emphasize the contraction. Limit depth of the heels if you feel any sort of stretch through the bottom of the foot during the exercise.Try to move through the ball of the foot rather than the base of the toes.", muscleGroup: .calves, presentation: "Machine Seated Calf Raises"),
            MuscleGroupExercises(name: "Dumbbell Calf Raise", image: UIImage(named: "dumbbellCalfRaise")!, description: "To do a calf raise with dumbbells, hold a dumbbell in each hand and stand with your feet about shoulder-width apart. Let your arms hang straight below your shoulders. Rise up onto your toes, then slowly return to the starting position. You'll feel tension in the muscles in the back of your lower legs.When you're doing calf raises, keep your back and knees straight. If you have trouble balancing, use a chair or pole for added stability.", muscleGroup: .calves, presentation: "Dumbbell Calf Raise")]
        exercisesList = exercisesList.filter { $0.muscleGroup == muscleGroup }
        
        
        tableView.backgroundColor = UIColor.white
        tableView.delegate = self
        tableView.dataSource = self
        
        titleMuscleGroup.text = muscleGroupsNames
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        tabBarController?.tabBar.isHidden = false
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return exercisesList.filter({ $0.muscleGroup == muscleGroup }).count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "muscleGroupExercises", for: indexPath) as? MuscleExercisesTableViewCell
        
        guard let tableViewCell = cell else { return UITableViewCell() }
        
        let exerciceList = exercisesList[indexPath.row]
        
        tableViewCell.exercisesImage.image = exerciceList.image
        tableViewCell.exercisesNameLabel.text = exerciceList.name
        
        return tableViewCell
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "ShowExercisesDetail" {
            if let indexPath = self.tableView.indexPathForSelectedRow {
                let exercisesVC = segue.destination as! ExercisesViewController
                exercisesVC.selectedExercise = exercisesList[indexPath.row]
            }
        }
    }
    
    
}

extension MuscleGroupDetailVC: UITableViewDelegate, UITableViewDataSource {
}
